### ISSUE TITLE
Consider relaxing JwtAlgorithm.DigSig

### ISSUE THREAD

**Issue by dzarras** [eu-digital-identity-wallet/eudi-lib-jvm-presentation-exchange-kt#141]
`JwtAlgorithm.DigSig` is defined as an enumeration. This limits the possible values that can be used and requires code changes to introduce support for new algorightms.

Given for instance no constants exist for `ESB256`, `ESB320`, `ESB384`, and `ESB512`, the following format fails to parse:
```json
{
  "format": {
    "mso_mdoc": {
      "alg": [
        "ES256",
        "ES384",
        "ES512",
        "EdDSA",
        "ESB256",
        "ESB320",
        "ESB384",
        "ESB512"
      ]
    }
  }
}
```

We must consider converting JwtAlgorithm.DigSig (or JwtAlgorithm) to a `value class`.

**Comment by babisRoutis** [comment]
Closing this. Won't be implemented due to the re-definition of format
