### ISSUE TITLE
Too strict  definition of Claim format designations

### ISSUE THREAD

**Issue by babisRoutis** [eu-digital-identity-wallet/eudi-lib-jvm-presentation-exchange-kt#142]
Presentation Exchange [contains](https://identity.foundation/presentation-exchange/spec/v2.0.0/#claim-format-designations) a section about the contents of an attribute named `format` which can be found either as a top-level element of presentation definition or with an `input_descriptor`.

This `format` is a JSON object having as attribute names claim formats coming by a [controlled registry](https://github.com/decentralized-identity/claim-format-registry/). In turn, each of these nested claim formats may point to another JSON Object which contains either an array `alg` or `proof_type` as defined in the [relevant](https://identity.foundation/claim-format-registry/schemas/presentation-definition-claim-format-designations.json) json schema.

Library reflects in its types the above rules, strictly. There are problems with this strictness:

OpenId4VP draft 20 uses claim formats that are not (yet) registered to the aforementioned Presentation Exchange controlled registry. In particular:

- `jwt_vc_json` & `jwt_vp_json` in [A.1.1](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-vc-signed-as-a-jwt-not-usin)
- `ac_vc` & `ac_vp` in [A.2](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-anoncreds)
- `mso_mdoc` in [A.3](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-iso-mobile-driving-license-)
- `sd+jwt-vc` to be added for `sd-jwt-vc` ([PR](https://github.com/openid/OpenID4VP/pull/115)). This doesn't only add a new value but redefines the contents of the relevant JSON to contain two arrays : `sd-jwt_alg_values` & `kb-jwt_alg_values`

So library-wise there are two options:
- Implement just the registered claims formats (current approach)
- Relax the `format` object accepting the fact that neither all keys are registered nor the contents of their value  

 The first is too restrictive, I guess. Perhaps we should go with the 2nd option.

**Comment by vafeini** [comment]
Indeed option 2 is a better way forward. At least until the set of formats is stabilized library should be more relaxed.
